# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka_data:/bitnami/kafka'
  ksql:
    image: docker.io/bitnami/ksql:7.3
    environment:
      - KSQL_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - 'ksql_data:/bitnami/ksql'
    depends_on:
      - kafka

volumes:
  kafka_data:
    driver: local
  ksql_data:
    driver: local
