apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: config
    repoURL: "https://github.com/KMD-A-S-CNAP/cnap-components-openshift-pipelines"
    targetRevision: HEAD
  project: argocd-cnap-app-of-apps-project
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: {}
  syncOptions:
    - CreateNamespace=true
