apiVersion: v1
kind: Pod
metadata:
  labels:
    name: hippo-to-clone
  name: VAR.POD_NAME.VAR
  namespace: postgres-operator
spec:
  volumes:
    - name: VAR.PVC_NAME.VAR
      persistentVolumeClaim:
        claimName: VAR.PVC_NAME.VAR
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: copier
      resources:
        limits:
          cpu: 150m
          memory: 512Mi
        requests:
          cpu: 150m
          memory: 512Mi
      volumeMounts:
        - mountPath: /mnt/VAR.PVC_NAME.VAR
          name: VAR.PVC_NAME.VAR
