apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-stack-monitoring-user-secret
stringData:
  url: https://elasticsearch-es-http.eck.svc:9200 #? na pewno to?
  username: elasticsearch-stack-monitoring-user
  password: REDACTED