# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mysqld-exporter:
    image: docker.io/bitnami/mysqld-exporter:0
    ports:
      - 9104:9104
    environment:
      - DATA_SOURCE_NAME='dbuser:dbpassword@(dbhost:3306)/'
