#!/bin/bash
current_url=$(git remote get-url origin) 

if [[ $current_url == *":"* ]]; then
  username=${current_url#*//}
  username=${username%%:*}
else
  read -p "Username: " username
fi

echo "Password: "
read -s password

if echo $current_url | grep -q "@"; then
  url="https://$username:$password@${current_url#*@}"
else
  url="https://$username:$password@${current_url#*//}"
fi

git remote set-url origin $url
