apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{"release.openshift.io/create-only":"true"},"name":"cluster"},"spec":{"identityProviders":[{"mappingMethod":"claim","name":"azureAD","openID":{"claims":{"email":["email"],"name":["name"],"preferredUsername":["upn","preferred_username","email"]},"clientID":"b4fd3472-696a-4397-ad90-16e20a008dbf","clientSecret":{"name":"cloudrunners-dk-ocp4aad"},"extraScopes":[],"issuer":"https://login.microsoftonline.com/1aaaea9d-df3e-4ce7-a55d-43de56e79442"},"type":"OpenID"}]}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2023-03-23T13:03:58Z"
  generation: 2
  managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
            .: {}
            "f:include.release.openshift.io/ibm-cloud-managed": {}
            "f:include.release.openshift.io/self-managed-high-availability": {}
            "f:include.release.openshift.io/single-node-developer": {}
            "f:release.openshift.io/create-only": {}
          "f:ownerReferences":
            .: {}
            'k:{"uid":"86f0f55a-ffd8-4da4-82a9-23b1a4d15c12"}': {}
        "f:spec": {}
      manager: cluster-version-operator
      operation: Update
      time: "2023-03-23T13:03:58Z"
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
            "f:kubectl.kubernetes.io/last-applied-configuration": {}
        "f:spec":
          "f:identityProviders": {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2023-03-23T14:46:10Z"
  name: cluster
  ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 86f0f55a-ffd8-4da4-82a9-23b1a4d15c12
  resourceVersion: "66761"
  uid: 64ec01ae-a7d8-49a9-8f47-17650a88bcbe
spec:
  identityProviders:
    - mappingMethod: claim
      name: azureAD
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - upn
            - preferred_username
            - email
        clientID: b4fd3472-696a-4397-ad90-16e20a008dbf
        clientSecret:
          name: cloudrunners-dk-ocp4aad
        extraScopes: []
        issuer: "https://login.microsoftonline.com/1aaaea9d-df3e-4ce7-a55d-43de56e79442"
      type: OpenID
  templates:
    login:
      name: login-template
    providerSelection:
      name: providers-template
