apiVersion: v1
kind: ServiceAccount
metadata:
  name: acr-tekton-triggers-sa
  namespace: mxb
  labels:
    app: acr-integration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acr-triggers-eventlistener-binding
  namespace: mxb
  labels:
    app: acr-integration
subjects:
  - kind: ServiceAccount
    name: acr-tekton-triggers-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acr-triggers-eventlistener-clusterbinding
  namespace: mxb
  labels:
    app: acr-integration
subjects:
  - kind: ServiceAccount
    name: acr-tekton-triggers-sa
    namespace: mxb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
