kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.quay.project_name }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.subscription.namespace }}
  annotations:
    openshift.io/node-selector: 'node-role.kubernetes.io/infra='
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "effect": "NoSchedule", "key":
      "node-role.kubernetes.io/infra"}
      ]
spec: {}
