apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2023-05-25T16:21:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: hippo-repo1
  namespace: postgres-crunchy
  resourceVersion: "167475558"
  uid: 39f750aa-0c83-4e90-bcfc-5eedb49d3d74
spec:
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: elephant-repo1-snapshot
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: elephant-repo1-snapshot
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-csi
  volumeMode: Filesystem
status:
  phase: Pending
