apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hippo-repo1
spec:
  storageClassName: managed-csi
  dataSource:
    name: elephant-repo1-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi