kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-creator-role-binding
  namespace: {{ .Values.subscription.namespace }}
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: installplan-manager-role-binding
  namespace: {{ .Values.subscription.namespace }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.subscription.namespace }}
roleRef:
  kind: Role
  name: installplan-manager
  apiGroup: rbac.authorization.k8s.io
