apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  finalizers:
    - noobaa.io/finalizer
  labels:
    app: noobaa
  name: noobaa-pv-backing-store
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  pvPool:
    numVolumes: 1
    resources:
      requests:
        storage: {{ .Values.noobaa.size }}
    storageClass: {{ .Values.noobaa.storageClass }}
  type: pv-pool
