apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  name: noobaa
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  dbResources:
    requests:
      cpu: "0.1"
      memory: 1Gi
  dbType: postgres
  coreResources:
    requests:
      cpu: "0.1"
      memory: 1Gi
