version: '2'
services:
  thanos:
    image: docker.io/bitnami/thanos:0
    command:
      - query
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:9090
    ports:
      - '9090:9090'